package com.avans.rentmycar.ui.home

import androidx.lifecycle.ViewModelProvider
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.fragment.navArgs
import com.avans.rentmycar.R
import com.avans.rentmycar.databinding.FragmentBookingDetailBinding

class BookingDetailFragment : Fragment() {

    // TODO: This was autogenerated. Find out if it is usefull or needed
//    companion object {
//        fun newInstance() = BookingDetailFragment()
//    }

    private lateinit var viewModel: BookingViewModel

    private lateinit var _binding: FragmentBookingDetailBinding
    private val binding get() = _binding


    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _binding = FragmentBookingDetailBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

//        val args: BookingDetailFragmentArgs by navArgs()
//        val bookingId = args.id

    }


    // TODO: This was autogenerated. Find out if it is usefull or needed
//    override fun onActivityCreated(savedInstanceState: Bundle?) {
//        super.onActivityCreated(savedInstanceState)
//        viewModel = ViewModelProvider(this).get(BookingViewModel::class.java)
//        // TODO: Use the ViewModel
//    }

}